-- Drop the existing check constraint
ALTER TABLE public.ai_change_tracking DROP CONSTRAINT IF EXISTS ai_change_tracking_change_type_check;

-- Add new check constraint that allows all change types generated by DiffBasedChangeTrackingService
ALTER TABLE public.ai_change_tracking ADD CONSTRAINT ai_change_tracking_change_type_check 
CHECK (change_type IN (
  'grammar', 'structure', 'dialogue', 'style',
  'insertion', 'deletion', 'replacement', 
  'capitalization', 'punctuation_correction', 'whitespace_adjustment'
));