// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zayyumerqynmimokwcro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpheXl1bWVycXlubWltb2t3Y3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTk1MDcsImV4cCI6MjA2MDU3NTUwN30.vC1AF6kf0kFtPABh0u5u_g8JVACKc4xXVe3w8lyCRMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);